version: 2

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 4
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - gocyclo
    - ineffassign
    - unconvert
    - unused
    - misspell
    - whitespace
    - bodyclose
    - prealloc
    - dupl
    - goconst
    - gocritic
    - revive

issues:
  exclude-rules:
    - path: ".*_test\\.go$"
      linters:
        - errcheck
        - gocyclo
        - goconst
        - revive
        - gosec
    - path: ^examples/.*
      linters:
        - unused
        - gosec
    - path: ^debug/.*
      linters:
        - unused
  max-issues-per-linter: 0
  max-same-issues: 0
