name: Deploy Documentation

on:
  push:
    branches:
      - main  # Set branch to deploy from
    paths:
      - 'docs/**'  # Only run workflow when docs directory changes
      - '.github/workflows/deploy-docs.yml'  # Or when this workflow file changes

  # Allow manual triggers from GitHub UI
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write  # Changed from 'read' to 'write' to allow commits
  pages: write
  id-token: write

# Allow only one concurrent deployment to avoid conflicts
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper deployment

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs  # The folder containing the content to deploy
          branch: gh-pages  # The branch to deploy to
          clean: true  # Clean the deployment branch of files not in the source folder
